//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agencies> Agencies { get; set; }
        public virtual DbSet<CoordinateKeys> CoordinateKeys { get; set; }
        public virtual DbSet<DefinedRoutes> DefinedRoutes { get; set; }
        public virtual DbSet<DeliveryData> DeliveryData { get; set; }
        public virtual DbSet<Factories> Factories { get; set; }
        public virtual DbSet<Filiations> Filiations { get; set; }
        public virtual DbSet<InnerEncryption> InnerEncryption { get; set; }
        public virtual DbSet<InnerEncryptionData> InnerEncryptionData { get; set; }
        public virtual DbSet<MilitaryCamps> MilitaryCamps { get; set; }
        public virtual DbSet<OperationalAreas> OperationalAreas { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetail { get; set; }
        public virtual DbSet<PlanetKeys> PlanetKeys { get; set; }
        public virtual DbSet<PlanetRoutes> PlanetRoutes { get; set; }
        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<References> References { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<RouteTypes> RouteTypes { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<SpaceShipCategories> SpaceShipCategories { get; set; }
        public virtual DbSet<SpaceShips> SpaceShips { get; set; }
        public virtual DbSet<SpaceShipTypes> SpaceShipTypes { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserCategories> UserCategories { get; set; }
        public virtual DbSet<UserRanks> UserRanks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ValidationCode> ValidationCode { get; set; }
        public virtual DbSet<Forms> Forms { get; set; }
    }
}
