//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinateKeys
    {
        public int idCoordinateKey { get; set; }
        public int idInnerEncryption { get; set; }
        public string Coordinate { get; set; }
        public string CoordinateKey { get; set; }
    
        public virtual InnerEncryption InnerEncryption { get; set; }
    }
}
