//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryData
    {
        public int idDeliveryData { get; set; }
        public string CodeDelivery { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int idPlanetOri { get; set; }
        public int idPlanetDest { get; set; }
        public int idSpaceShip { get; set; }
    }
}
