//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public int idForm { get; set; }
        public string icon { get; set; }
        public string descripcio { get; set; }
        public string dll { get; set; }
        public string form { get; set; }
        public int accessLevel { get; set; }
        public Nullable<int> red { get; set; }
        public Nullable<int> green { get; set; }
        public Nullable<int> blue { get; set; }
    }
}
