//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnerEncryptionData
    {
        public int idInnerEncryptionData { get; set; }
        public Nullable<int> IdInnerEncryption { get; set; }
        public string Word { get; set; }
        public string Numbers { get; set; }
        public Nullable<short> OrderData { get; set; }
    
        public virtual InnerEncryption InnerEncryption { get; set; }
    }
}
