//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryCamps
    {
        public int idMilitaryCamp { get; set; }
        public string CodeCamp { get; set; }
        public string DescCamp { get; set; }
        public Nullable<int> idPlanet { get; set; }
    
        public virtual Planets Planets { get; set; }
    }
}
