//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceShips
    {
        public int idSpaceShip { get; set; }
        public Nullable<int> idSpaceShipType { get; set; }
        public string CodeSpaceShip { get; set; }
        public string IPSpaceShip { get; set; }
        public string PortSpaceShip { get; set; }
        public string PortSpaceShip1 { get; set; }
    
        public virtual SpaceShipTypes SpaceShipTypes { get; set; }
    }
}
