//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int idUser { get; set; }
        public string CodeUser { get; set; }
        public string UserName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> idUserRank { get; set; }
        public Nullable<int> idUserCategory { get; set; }
        public string Photo { get; set; }
        public Nullable<int> idPlanet { get; set; }
        public Nullable<int> idSpecie { get; set; }
    
        public virtual Planets Planets { get; set; }
        public virtual Species Species { get; set; }
        public virtual UserCategories UserCategories { get; set; }
        public virtual UserRanks UserRanks { get; set; }
    }
}
