//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMS
    {
        public int ID { get; set; }
        public string IMG { get; set; }
        public string DESCRIPCIO { get; set; }
        public string DLL { get; set; }
        public Nullable<int> RANG { get; set; }
        public string NOMFORMULARI { get; set; }
    }
}
